# only nginx is going to be exposed publicly

services:
  # The Backend API Service. No ports are exposed to the host.
  backend:
    build: ./backend
    # The 'restart: always' policy ensures the container restarts if it fails.
    restart: always

    #for logging to work, must do the following:
    # sudo nano /etc/logrotate.d/docker-compose-logs
    # past the following into it, targeting the log files for all Docker containers.
    # /var/lib/docker/containers/*/*.log {
    #     daily
    #     rotate 7
    #     compress
    #     missingok
    #     notifempty
    #     copytruncate
    # }
    #then rebuilt the docker containers

    logging:
      driver: "json-file"
      options:
        max-size: "50m" # A decent size before docker rotates the log files by itself

  # The Frontend React App Service. No ports are exposed to the host.
  frontend:
    build: ./frontend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  nginx:
    # We build the proxy image from the nginx directory
    build: ./nginx
    # It's the only service that exposes ports to the host machine.
    # Port 80 on the host is mapped to port 80 in the container.
    ports:
      - "80:80"
      - "443:443"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

    # Adding volumes section for Certbot and Nginx config
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/html
    # It depends on the other services being available before it starts.
    depends_on:
      - backend
      - frontend
